/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as MarchRouteImport } from './routes/march'
import { Route as EnvironmentRouteImport } from './routes/environment'
import { Route as DatabaseRouteImport } from './routes/database'
import { Route as CodeRouteImport } from './routes/code'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnvironmentIndexRouteImport } from './routes/environment.index'
import { Route as EnvironmentEnvironmentIdRouteImport } from './routes/environment.$environmentId'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const MarchRoute = MarchRouteImport.update({
  id: '/march',
  path: '/march',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentRoute = EnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => rootRouteImport,
} as any)
const DatabaseRoute = DatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentIndexRoute = EnvironmentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnvironmentRoute,
} as any)
const EnvironmentEnvironmentIdRoute =
  EnvironmentEnvironmentIdRouteImport.update({
    id: '/$environmentId',
    path: '/$environmentId',
    getParentRoute: () => EnvironmentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/database': typeof DatabaseRoute
  '/environment': typeof EnvironmentRouteWithChildren
  '/march': typeof MarchRoute
  '/test': typeof TestRoute
  '/environment/$environmentId': typeof EnvironmentEnvironmentIdRoute
  '/environment/': typeof EnvironmentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/database': typeof DatabaseRoute
  '/march': typeof MarchRoute
  '/test': typeof TestRoute
  '/environment/$environmentId': typeof EnvironmentEnvironmentIdRoute
  '/environment': typeof EnvironmentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/code': typeof CodeRoute
  '/database': typeof DatabaseRoute
  '/environment': typeof EnvironmentRouteWithChildren
  '/march': typeof MarchRoute
  '/test': typeof TestRoute
  '/environment/$environmentId': typeof EnvironmentEnvironmentIdRoute
  '/environment/': typeof EnvironmentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/code'
    | '/database'
    | '/environment'
    | '/march'
    | '/test'
    | '/environment/$environmentId'
    | '/environment/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/code'
    | '/database'
    | '/march'
    | '/test'
    | '/environment/$environmentId'
    | '/environment'
  id:
    | '__root__'
    | '/'
    | '/code'
    | '/database'
    | '/environment'
    | '/march'
    | '/test'
    | '/environment/$environmentId'
    | '/environment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CodeRoute: typeof CodeRoute
  DatabaseRoute: typeof DatabaseRoute
  EnvironmentRoute: typeof EnvironmentRouteWithChildren
  MarchRoute: typeof MarchRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/march': {
      id: '/march'
      path: '/march'
      fullPath: '/march'
      preLoaderRoute: typeof MarchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environment': {
      id: '/environment'
      path: '/environment'
      fullPath: '/environment'
      preLoaderRoute: typeof EnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/database': {
      id: '/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof DatabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environment/': {
      id: '/environment/'
      path: '/'
      fullPath: '/environment/'
      preLoaderRoute: typeof EnvironmentIndexRouteImport
      parentRoute: typeof EnvironmentRoute
    }
    '/environment/$environmentId': {
      id: '/environment/$environmentId'
      path: '/$environmentId'
      fullPath: '/environment/$environmentId'
      preLoaderRoute: typeof EnvironmentEnvironmentIdRouteImport
      parentRoute: typeof EnvironmentRoute
    }
  }
}

interface EnvironmentRouteChildren {
  EnvironmentEnvironmentIdRoute: typeof EnvironmentEnvironmentIdRoute
  EnvironmentIndexRoute: typeof EnvironmentIndexRoute
}

const EnvironmentRouteChildren: EnvironmentRouteChildren = {
  EnvironmentEnvironmentIdRoute: EnvironmentEnvironmentIdRoute,
  EnvironmentIndexRoute: EnvironmentIndexRoute,
}

const EnvironmentRouteWithChildren = EnvironmentRoute._addFileChildren(
  EnvironmentRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CodeRoute: CodeRoute,
  DatabaseRoute: DatabaseRoute,
  EnvironmentRoute: EnvironmentRouteWithChildren,
  MarchRoute: MarchRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
